=== Fireaxxe/CSCU9T4/Practicals/XML2 Practical/contacts.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">
	<xs:element name="contacts">
		<xs:complexType>
			<xs:sequence>
				<xs:element name="contact" minOccurs="1" maxOccurs="unbounded">
					<xs:complexType>
						<xs:sequence>
							<xs:element name="name">
								<xs:complexType>
									<xs:sequence>
										<xs:element name="first" type="xs:string"/>
										<xs:element name="middle" type="xs:string" minOccurs="0"/>
										<xs:element name="last" type="xs:string"/>
									</xs:sequence>
								</xs:complexType>
							</xs:element>
							<xs:element name="age" type="xs:int" minOccurs="0"/>
							<xs:element name="location">
								<xs:complexType>
									<xs:choice>
										<xs:element name="postcode" type="xs:string"/>
										<xs:element name="city" type="xs:string"/>										
									</xs:choice>
								</xs:complexType>
							</xs:element>
							<xs:element name="phone" type="xs:string"/>
							<xs:element name="occupation" type="xs:string"/>
						</xs:sequence>
					</xs:complexType>
				</xs:element>
			</xs:sequence>
		</xs:complexType>
	</xs:element>
</xs:schema>

=== Fireaxxe/CSCU9T4/Practicals/XML2 Practical/contacts.xml
<?xml version="1.0" encoding="UTF-8"?>
<contacts xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
xsi:noNamespaceSchemaLocation="contacts.xsd">
	<contact>
		<name>
			<first>Anne</first>
			<middle>Kate</middle>
			<last>Fawcett</last>
		</name>
		<location>
			<postcode>FK9 4LA</postcode>
		</location>
		<phone>(01786) 445587</phone>
		<occupation>Engineer</occupation>
	</contact>
	<contact>
		<name>
			<first>Andy</first>
			<last>Murray</last>
		</name>
		<age>27</age>
		<location>
			<city>Dunblane</city>
		</location>
		<phone>(01786) 455567</phone>
		<occupation>Tennis Player</occupation>
	</contact>
</contacts>
