=== Fireaxxe/CSCU9T4/Assignments/XML Assignment/Q1/survey.xsd
<?xml version="1.0" encoding="utf-8" ?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">
	<xs:element name="document">
		<xs:complexType>
			<xs:sequence>
				<xs:element name="person" minOccurs="0" maxOccurs="unbounded">
					<xs:complexType>
						<xs:sequence>
							<xs:element name="month">
								<xs:simpleType>
									<xs:restriction base="xs:string">
										<xs:enumeration value="January"/>
										<xs:enumeration value="February"/>
										<xs:enumeration value="March"/>
										<xs:enumeration value="April"/>
										<xs:enumeration value="May"/>
										<xs:enumeration value="June"/>
										<xs:enumeration value="July"/>
										<xs:enumeration value="August"/>
										<xs:enumeration value="September"/>
										<xs:enumeration value="October"/>
										<xs:enumeration value="November"/>
										<xs:enumeration value="December"/>
									</xs:restriction>
								</xs:simpleType>
							</xs:element>
							<xs:element name="platform">
								<xs:simpleType>
									<xs:restriction base="xs:string">
										<xs:enumeration value="Android"/>
										<xs:enumeration value="iOS"/>
										<xs:enumeration value="Both"/>
									</xs:restriction>
								</xs:simpleType>
							</xs:element>
							<xs:element name="team">
								<xs:simpleType>
									<xs:restriction base="xs:string">
										<xs:enumeration value="Instinct (Yellow)"/>
										<xs:enumeration value="Mystic (Blue)"/>
										<xs:enumeration value="Valor (Red)"/>
										<xs:enumeration value="None (White)"/>
									</xs:restriction>
								</xs:simpleType>
							</xs:element>
							<xs:element name="level">
								<xs:simpleType>
									<xs:restriction base="xs:integer">
										<xs:minInclusive value="1"/>
										<xs:maxInclusive value="40"/>
									</xs:restriction>
								</xs:simpleType>
							</xs:element>
							<xs:element name="caught">
								<xs:simpleType>
									<xs:union>
										<xs:simpleType>
											<xs:restriction base="xs:integer">
												<xs:minInclusive value="1"/>
												<xs:maxExclusive value="1000"/>
											</xs:restriction>
										</xs:simpleType>
										<xs:simpleType>
											<xs:restriction base="xs:integer">
												<xs:minInclusive value="1000"/>
												<xs:maxExclusive value="5000"/>
											</xs:restriction>
										</xs:simpleType>
										<xs:simpleType>
											<xs:restriction base="xs:integer">
												<xs:minInclusive value="5000"/>
												<xs:maxExclusive value="20000"/>
											</xs:restriction>
										</xs:simpleType>
										<xs:simpleType>
											<xs:restriction base="xs:integer">
												<xs:minInclusive value="20000"/>
											</xs:restriction>
										</xs:simpleType>
									</xs:union>
								</xs:simpleType>
							</xs:element>
							<xs:element name="distance">
								<xs:simpleType>
									<xs:union>
										<xs:simpleType id="NoMedal">
											<xs:restriction base="xs:integer">
												<xs:minInclusive value="0"/>
												<xs:maxInclusive value="9"/>
											</xs:restriction>
										</xs:simpleType>
										<xs:simpleType id="Bronze">
											<xs:restriction base="xs:integer">
												<xs:minInclusive value="10"/>
												<xs:maxInclusive value="99"/>
											</xs:restriction>
										</xs:simpleType>
										<xs:simpleType id="Silver">
											<xs:restriction base="xs:integer">
												<xs:minInclusive value="100"/>
												<xs:maxInclusive value="999"/>
											</xs:restriction>
										</xs:simpleType>
										<xs:simpleType id="Gold">
											<xs:restriction base="xs:integer">
												<xs:minInclusive value="1000"/>                                                
											</xs:restriction>
										</xs:simpleType>
									</xs:union>
								</xs:simpleType>
							</xs:element>
						</xs:sequence>
						<xs:attribute name="id" type="xs:unsignedShort" use="optional" />
					</xs:complexType>
				</xs:element>
			</xs:sequence>
		</xs:complexType>
	</xs:element>
</xs:schema>

=== Fireaxxe/CSCU9T4/Assignments/XML Assignment/Q1/survey.xml
<?xml version="1.0" encoding="UTF-8"?>
<document xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
xsi:noNamespaceSchemaLocation="survey.xsd">
	<person id="1">
		<month>June</month>
		<platform>Android</platform>
		<team>Mystic (Blue)</team>
		<level>25</level>
		<caught>1000</caught>
		<distance>202</distance>
	</person>
	<person id="2">
		<month>June</month>
		<platform>Android</platform>
		<team>Mystic (Blue)</team>
		<level>32</level>
		<caught>1000</caught>
		<distance>944</distance>
	</person>
	<person id="3">
		<month>June</month>
		<platform>Android</platform>
		<team>Instinct (Yellow)</team>
		<level>29</level>
		<caught>2000</caught>
		<distance>487</distance>
	</person>
	<person id="4">
		<month>June</month>
		<platform>Android</platform>
		<team>Valor (Red)</team>
		<level>29</level>
		<caught>2000</caught>
		<distance>324</distance>
	</person>
	<person id="5">
		<month>June</month>
		<platform>Android</platform>
		<team>Mystic (Blue)</team>
		<level>28</level>
		<caught>2000</caught>
		<distance>350</distance>
	</person>
	<person id="6">
		<month>June</month>
		<platform>Android</platform>
		<team>Valor (Red)</team>
		<level>32</level>
		<caught>10000</caught>
		<distance>888</distance>
	</person>
	<person id="7">
		<month>June</month>
		<platform>iOS</platform>
		<team>Instinct (Yellow)</team>
		<level>33</level>
		<caught>20000</caught>
		<distance>951</distance>
	</person>
	<person id="8">
		<month>June</month>
		<platform>Android</platform>
		<team>Mystic (Blue)</team>
		<level>35</level>
		<caught>1000</caught>
		<distance>1935</distance>
	</person>
	<person id="9">
		<month>June</month>
		<platform>Android</platform>
		<team>Mystic (Blue)</team>
		<level>30</level>
		<caught>2000</caught>
		<distance>708</distance>
	</person>
	<person id="10">
		<month>June</month>
		<platform>iOS</platform>
		<team>Mystic (Blue)</team>
		<level>33</level>
		<caught>2000</caught>
		<distance>907</distance>
	</person>
	<person id="11">
		<month>June</month>
		<platform>Android</platform>
		<team>Instinct (Yellow)</team>
		<level>32</level>
		<caught>3000</caught>
		<distance>767</distance>
	</person>
	<person id="12">
		<month>June</month>
		<platform>Android</platform>
		<team>Instinct (Yellow)</team>
		<level>33</level>
		<caught>1000</caught>
		<distance>1060</distance>
	</person>
	<person id="13">
		<month>June</month>
		<platform>Android</platform>
		<team>Mystic (Blue)</team>
		<level>31</level>
		<caught>3000</caught>
		<distance>915</distance>
	</person>
	<person id="14">
		<month>June</month>
		<platform>Android</platform>
		<team>Valor (Red)</team>
		<level>25</level>
		<caught>3000</caught>
		<distance>290</distance>
	</person>
	<person id="15">
		<month>July</month>
		<platform>iOS</platform>
		<team>Valor (Red)</team>
		<level>33</level>
		<caught>5000</caught>
		<distance>782</distance>
	</person>
	<person id="16">
		<month>July</month>
		<platform>Android</platform>
		<team>Valor (Red)</team>
		<level>30</level>
		<caught>2000</caught>
		<distance>240</distance>
	</person>
	<person id="17">
		<month>July</month>
		<platform>Android</platform>
		<team>Mystic (Blue)</team>
		<level>37</level>
		<caught>2000</caught>
		<distance>1502</distance>
	</person>
	<person id="18">
		<month>July</month>
		<platform>Android</platform>
		<team>Mystic (Blue)</team>
		<level>39</level>
		<caught>5000</caught>
		<distance>2058</distance>
	</person>
	<person id="19">
		<month>July</month>
		<platform>iOS</platform>
		<team>Mystic (Blue)</team>
		<level>34</level>
		<caught>2000</caught>
		<distance>1181</distance>
	</person>
	<person id="20">
		<month>July</month>
		<platform>iOS</platform>
		<team>Valor (Red)</team>
		<level>20</level>
		<caught>3000</caught>
		<distance>72</distance>
	</person>
	<person id="21">
		<month>July</month>
		<platform>iOS</platform>
		<team>Instinct (Yellow)</team>
		<level>31</level>
		<caught>5000</caught>
		<distance>982</distance>
	</person>
	<person id="22">
		<month>July</month>
		<platform>iOS</platform>
		<team>Instinct (Yellow)</team>
		<level>34</level>
		<caught>3000</caught>
		<distance>1010</distance>
	</person>
	<person id="23">
		<month>July</month>
		<platform>Android</platform>
		<team>Valor (Red)</team>
		<level>37</level>
		<caught>5000</caught>
		<distance>5760</distance>
	</person>
	<person id="24">
		<month>July</month>
		<platform>iOS</platform>
		<team>Mystic (Blue)</team>
		<level>24</level>
		<caught>3000</caught>
		<distance>121</distance>
	</person>
	<person id="25">
		<month>July</month>
		<platform>iOS</platform>
		<team>Valor (Red)</team>
		<level>22</level>
		<caught>2000</caught>
		<distance>76</distance>
	</person>
	<person id="26">
		<month>July</month>
		<platform>iOS</platform>
		<team>Valor (Red)</team>
		<level>25</level>
		<caught>10000</caught>
		<distance>212</distance>
	</person>
	<person id="27">
		<month>July</month>
		<platform>iOS</platform>
		<team>Instinct (Yellow)</team>
		<level>26</level>
		<caught>2000</caught>
		<distance>208</distance>
	</person>
	<person id="28">
		<month>July</month>
		<platform>Android</platform>
		<team>Valor (Red)</team>
		<level>27</level>
		<caught>5000</caught>
		<distance>700</distance>
	</person>
	<person id="29">
		<month>July</month>
		<platform>iOS</platform>
		<team>Mystic (Blue)</team>
		<level>27</level>
		<caught>2000</caught>
		<distance>266</distance>
	</person>
	<person id="30">
		<month>July</month>
		<platform>Android</platform>
		<team>Valor (Red)</team>
		<level>30</level>
		<caught>2000</caught>
		<distance>643</distance>
	</person>
	<person id="31">
		<month>July</month>
		<platform>iOS</platform>
		<team>Valor (Red)</team>
		<level>26</level>
		<caught>3000</caught>
		<distance>355</distance>
	</person>
	<person id="32">
		<month>July</month>
		<platform>iOS</platform>
		<team>Mystic (Blue)</team>
		<level>32</level>
		<caught>5000</caught>
		<distance>530</distance>
	</person>
	<person id="33">
		<month>July</month>
		<platform>iOS</platform>
		<team>Valor (Red)</team>
		<level>27</level>
		<caught>5000</caught>
		<distance>392</distance>
	</person>
	<person id="34">
		<month>July</month>
		<platform>Android</platform>
		<team>Mystic (Blue)</team>
		<level>27</level>
		<caught>3000</caught>
		<distance>550</distance>
	</person>
	<person id="35">
		<month>July</month>
		<platform>iOS</platform>
		<team>Instinct (Yellow)</team>
		<level>29</level>
		<caught>2000</caught>
		<distance>232</distance>
	</person>
	<person id="36">
		<month>July</month>
		<platform>iOS</platform>
		<team>Mystic (Blue)</team>
		<level>29</level>
		<caught>3000</caught>
		<distance>859</distance>
	</person>
	<person id="37">
		<month>July</month>
		<platform>iOS</platform>
		<team>Mystic (Blue)</team>
		<level>31</level>
		<caught>3000</caught>
		<distance>600</distance>
	</person>
	<person id="38">
		<month>July</month>
		<platform>Android</platform>
		<team>Mystic (Blue)</team>
		<level>30</level>
		<caught>3000</caught>
		<distance>358</distance>
	</person>
	<person id="39">
		<month>July</month>
		<platform>Android</platform>
		<team>Instinct (Yellow)</team>
		<level>26</level>
		<caught>3000</caught>
		<distance>205</distance>
	</person>
	<person id="40">
		<month>July</month>
		<platform>Android</platform>
		<team>Mystic (Blue)</team>
		<level>29</level>
		<caught>5000</caught>
		<distance>710</distance>
	</person>
	<person id="41">
		<month>July</month>
		<platform>Android</platform>
		<team>Valor (Red)</team>
		<level>29</level>
		<caught>5000</caught>
		<distance>415</distance>
	</person>
	<person id="42">
		<month>July</month>
		<platform>iOS</platform>
		<team>Valor (Red)</team>
		<level>30</level>
		<caught>5000</caught>
		<distance>1122</distance>
	</person>
	<person id="43">
		<month>July</month>
		<platform>Android</platform>
		<team>Instinct (Yellow)</team>
		<level>29</level>
		<caught>10000</caught>
		<distance>706</distance>
	</person>
	<person id="44">
		<month>July</month>
		<platform>Android</platform>
		<team>Valor (Red)</team>
		<level>35</level>
		<caught>5000</caught>
		<distance>1263</distance>
	</person>
	<person id="45">
		<month>July</month>
		<platform>Android</platform>
		<team>Instinct (Yellow)</team>
		<level>32</level>
		<caught>2000</caught>
		<distance>437</distance>
	</person>
	<person id="46">
		<month>July</month>
		<platform>iOS</platform>
		<team>Instinct (Yellow)</team>
		<level>30</level>
		<caught>3000</caught>
		<distance>452</distance>
	</person>
	<person id="47">
		<month>July</month>
		<platform>Android</platform>
		<team>Valor (Red)</team>
		<level>28</level>
		<caught>5000</caught>
		<distance>5000</distance>
	</person>
	<person id="48">
		<month>July</month>
		<platform>iOS</platform>
		<team>Instinct (Yellow)</team>
		<level>29</level>
		<caught>3000</caught>
		<distance>387</distance>
	</person>
	<person id="49">
		<month>July</month>
		<platform>Android</platform>
		<team>Mystic (Blue)</team>
		<level>31</level>
		<caught>5000</caught>
		<distance>951</distance>
	</person>
	<person id="50">
		<month>July</month>
		<platform>Android</platform>
		<team>Instinct (Yellow)</team>
		<level>30</level>
		<caught>5000</caught>
		<distance>388</distance>
	</person>
	<person id="51">
		<month>July</month>
		<platform>iOS</platform>
		<team>Valor (Red)</team>
		<level>30</level>
		<caught>3000</caught>
		<distance>619</distance>
	</person>
	<person id="52">
		<month>July</month>
		<platform>Android</platform>
		<team>Valor (Red)</team>
		<level>28</level>
		<caught>5000</caught>
		<distance>201</distance>
	</person>
	<person id="53">
